name: mypytorch
channels:
  - anaconda
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - asttokens=2.4.1=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bottleneck=1.3.7=py311hd7041d2_0
  - brotli=1.0.9=h2bbff1b_7
  - brotli-bin=1.0.9=h2bbff1b_7
  - brotli-python=1.0.9=py311hd77b12b_7
  - bzip2=1.0.8=h2bbff1b_5
  - ca-certificates=2024.2.2=h56e8100_0
  - certifi=2024.2.2=py311haa95532_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.2.1=pyhd8ed1ab_0
  - contourpy=1.2.0=py311h59b6b97_0
  - cuda-cccl=12.4.99=0
  - cuda-cudart=12.1.105=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-libraries-dev=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvrtc-dev=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.99=0
  - cuda-opencl-dev=12.4.99=0
  - cuda-profiler-api=12.4.99=0
  - cuda-runtime=12.1.0=0
  - cudatoolkit=11.3.1=h59b6b97_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.8.1=py311h12c1d0e_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - filelock=3.13.1=py311haa95532_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - gmpy2=2.1.2=py311h7f96b67_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.4=py311haa95532_0
  - importlib-metadata=7.0.2=pyha770c72_0
  - importlib_metadata=7.0.2=hd8ed1ab_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.3=pyha63f2e9_0
  - ipython=8.22.2=pyh7428d3b_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - jinja2=3.1.3=py311haa95532_0
  - joblib=1.2.0=py311haa95532_0
  - jpeg=9e=h2bbff1b_1
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.7.1=py311h1ea47a8_0
  - kiwisolver=1.4.4=py311hd77b12b_0
  - krb5=1.20.1=h5b6d351_0
  - lerc=3.0=hd77b12b_0
  - libbrotlicommon=1.0.9=h2bbff1b_7
  - libbrotlidec=1.0.9=h2bbff1b_7
  - libbrotlienc=1.0.9=h2bbff1b_7
  - libclang=14.0.6=default_hb5a9fac_1
  - libclang13=14.0.6=default_h8e68704_1
  - libcublas=12.1.0.26=0
  - libcublas-dev=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufft-dev=11.0.2.4=0
  - libcurand=10.3.5.119=0
  - libcurand-dev=10.3.5.119=0
  - libcusolver=11.4.4.55=0
  - libcusolver-dev=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libcusparse-dev=12.0.2.55=0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_0
  - libjpeg-turbo=2.0.0=h196d8e1_0
  - libnpp=12.0.2.50=0
  - libnpp-dev=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjitlink-dev=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libnvjpeg-dev=12.1.1.14=0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=12.17=h906ac69_0
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.44.2=h2bbff1b_0
  - libwebp-base=1.3.2=h2bbff1b_0
  - lz4-c=1.9.4=h2bbff1b_0
  - markupsafe=2.1.3=py311h2bbff1b_0
  - matplotlib=3.8.0=py311haa95532_0
  - matplotlib-base=3.8.0=py311hf62ec03_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py311h2bbff1b_1
  - mkl_fft=1.3.8=py311h2bbff1b_0
  - mkl_random=1.2.4=py311h59b6b97_0
  - mpc=1.1.0=h7edee0f_1
  - mpfr=4.0.2=h62dcd97_1
  - mpir=3.0.0=hec2e145_1
  - mpmath=1.3.0=py311haa95532_0
  - munkres=1.1.4=py_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - networkx=3.1=py311haa95532_0
  - numexpr=2.8.7=py311h1fcbade_0
  - numpy=1.24.3=py311hdab7c0b_1
  - numpy-base=1.24.3=py311hd01c5d8_1
  - openjpeg=2.4.0=h4fc8c34_0
  - openssl=3.2.1=hcfcfb64_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.2.1=py311hea22821_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=10.2.0=py311h2bbff1b_0
  - pip=23.3.1=py311haa95532_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - ply=3.11=py311haa95532_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py311ha68e1ae_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyparsing=3.0.9=py311haa95532_0
  - pyqt=5.15.10=py311hd77b12b_0
  - pyqt5-sip=12.13.0=py311h2bbff1b_0
  - pysocks=1.7.1=py311haa95532_0
  - python=3.11.5=he1021f5_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.11=2_cp311
  - pytorch=2.2.1=py3.11_cuda12.1_cudnn8_0
  - pytorch-cuda=12.1=hde6ce7c_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3.post1=py311haa95532_0
  - pywin32=306=py311h12c1d0e_2
  - pyyaml=6.0.1=py311h2bbff1b_0
  - pyzmq=25.1.2=py311h9250fbb_0
  - qt-main=5.15.2=h19c9488_10
  - requests=2.31.0=py311haa95532_1
  - scikit-learn=1.3.0=py311hf62ec03_0
  - scipy=1.11.4=py311hc1ccb85_0
  - setuptools=68.2.2=py311haa95532_0
  - sip=6.7.12=py311hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.41.2=h2bbff1b_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=py311haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h2bbff1b_0
  - tornado=6.4=py311ha68e1ae_0
  - tqdm=4.65.0=py311h746a85d_0
  - traitlets=5.14.1=pyhd8ed1ab_0
  - typing_extensions=4.9.0=py311haa95532_1
  - tzdata=2024a=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_0
  - urllib3=2.1.0=py311haa95532_1
  - vc=14.2=h21ff451_1
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - wheel=0.41.2=py311haa95532_0
  - win_inet_pton=1.1.0=py311haa95532_0
  - xz=5.4.6=h8cc25b3_0
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=h63175ca_1
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.5=hd43e919_0
  - pip:
      - kaggle==1.5.8
      - torchaudio==2.2.1
      - torchvision==0.17.1
prefix: C:\Users\sx119\.conda\envs\mypytorch
